from django.urls import path
from . import views
from . import commercial_views
from . import pedagogical_views
from .auth_views import RequiredPasswordChangeView
from . import user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('operacional/', views.operational_home, name='operational_home'),
    path('auditoria/', views.admin_activity_history, name='admin_activity_history'),
    path('auditoria.csv', views.admin_activity_history_csv, name='admin_activity_history_csv'),
    path('backups/', views.backups, name='backups'),
    path('backups/<str:backup_name>/download/', views.download_local_backup, name='backup_download'),
    path('gestao-comercial/tipos-de-funis/', commercial_views.funnel_types_list, name='commercial_funnel_types'),
    path('gestao-comercial/tipos-de-funis/novo/', commercial_views.funnel_type_create, name='funnel_type_create'),
    path('gestao-comercial/tipos-de-funis/<int:funnel_type_id>/editar/', commercial_views.funnel_type_edit, name='funnel_type_edit'),
    path('gestao-comercial/tipos-de-funis/<int:funnel_type_id>/alternar-status/', commercial_views.funnel_type_toggle, name='funnel_type_toggle'),
    path('gestao-comercial/tipos-de-funis/<int:funnel_type_id>/excluir/', commercial_views.funnel_type_delete, name='funnel_type_delete'),
    path('gestao-comercial/funis/etapas/', commercial_views.funnel_stages_list, name='commercial_funnel_stages'),
    path('gestao-comercial/funis/etapas/novo/', commercial_views.funnel_stage_create, name='funnel_stage_create'),
    path('gestao-comercial/funis/etapas/<int:stage_id>/editar/', commercial_views.funnel_stage_edit, name='funnel_stage_edit'),
    path('gestao-comercial/funis/etapas/<int:stage_id>/alternar-status/', commercial_views.funnel_stage_toggle, name='funnel_stage_toggle'),
    path('gestao-comercial/funis/etapas/<int:stage_id>/excluir/', commercial_views.funnel_stage_delete, name='funnel_stage_delete'),
    path('gestao-comercial/funis/oportunidades/origens/', commercial_views.opportunity_origins_list, name='commercial_opportunity_origins'),
    path('gestao-comercial/funis/oportunidades/origens/novo/', commercial_views.opportunity_origin_create, name='opportunity_origin_create'),
    path('gestao-comercial/funis/oportunidades/origens/<int:origin_id>/editar/', commercial_views.opportunity_origin_edit, name='opportunity_origin_edit'),
    path('gestao-comercial/funis/oportunidades/origens/<int:origin_id>/alternar-status/', commercial_views.opportunity_origin_toggle, name='opportunity_origin_toggle'),
    path('gestao-comercial/funis/oportunidades/origens/<int:origin_id>/excluir/', commercial_views.opportunity_origin_delete, name='opportunity_origin_delete'),
    path('gestao-comercial/modelos-de-funis/', commercial_views.funnel_models_list, name='commercial_funnel_models'),
    path('gestao-comercial/modelos-de-funis/novo/', commercial_views.funnel_model_create, name='funnel_model_create'),
    path('gestao-comercial/modelos-de-funis/<int:model_id>/editar/', commercial_views.funnel_model_edit, name='funnel_model_edit'),
    path('gestao-comercial/modelos-de-funis/<int:model_id>/alternar-status/', commercial_views.funnel_model_toggle, name='funnel_model_toggle'),
    path('gestao-comercial/modelos-de-funis/<int:model_id>/excluir/', commercial_views.funnel_model_delete, name='funnel_model_delete'),
    path('gestao-comercial/funis/gestao/', commercial_views.commercial_funnels_list, name='commercial_funnels'),
    path('gestao-comercial/funis/gestao/novo/', commercial_views.commercial_funnel_create, name='commercial_funnel_create'),
    path('gestao-comercial/funis/gestao/<int:funnel_id>/editar/', commercial_views.commercial_funnel_edit, name='commercial_funnel_edit'),
    path('gestao-comercial/funis/gestao/<int:funnel_id>/alternar-status/', commercial_views.commercial_funnel_toggle, name='commercial_funnel_toggle'),
    path('acompanhamento/comercial/', commercial_views.commercial_dashboard, name='commercial_dashboard'),
    path('acompanhamento/agenda/', pedagogical_views.commercial_lesson_agenda, name='commercial_lesson_agenda'),
    path('acompanhamento/agenda/sincronizar-sponte/', pedagogical_views.commercial_lessons_sync_sponte, name='commercial_lessons_sync_sponte'),
    path('acompanhamento/funis/', commercial_views.commercial_funnel_board, name='commercial_funnel_board'),
    path('acompanhamento/oportunidades/', commercial_views.commercial_opportunities_list, name='commercial_opportunities'),
    path('acompanhamento/oportunidades/nova/', commercial_views.commercial_opportunity_create, name='commercial_opportunity_create'),
    path('acompanhamento/oportunidades/<int:opportunity_id>/editar/', commercial_views.commercial_opportunity_edit, name='commercial_opportunity_edit'),
    path('acompanhamento/oportunidades/<int:opportunity_id>/alternar-status/', commercial_views.commercial_opportunity_toggle, name='commercial_opportunity_toggle'),
    path('acompanhamento/indicadores/', views.commercial_indicators, name='commercial_indicators'),
    path('acompanhamento/metas/', views.commercial_goals, name='commercial_goals'),
    path('instrutor/', pedagogical_views.instructor_dashboard, name='instructor_dashboard'),
    path('instrutor/agenda/', pedagogical_views.instructor_agenda, name='instructor_agenda'),
    path('instrutor/importar-sponte/', pedagogical_views.instructor_import_sponte, name='instructor_import_sponte'),
    path('gestao-pedagogica/agenda-de-aulas/', pedagogical_views.lesson_agenda, name='pedagogical_class_schedule'),
    path('gestao-pedagogica/agenda-de-aulas/sincronizar-sponte/', pedagogical_views.lessons_sync_sponte, name='pedagogical_lessons_sync_sponte'),
    path('gestao-pedagogica/agenda-de-aulas/nova/', pedagogical_views.lesson_create, name='pedagogical_lesson_create'),
    path('gestao-pedagogica/agenda-de-aulas/<int:lesson_id>/editar/', pedagogical_views.lesson_edit, name='pedagogical_lesson_edit'),
    path('gestao-pedagogica/aulas-experimentais/', pedagogical_views.trial_lessons, name='pedagogical_trial_lessons'),
    path('gestao-pedagogica/feedback-aula/', pedagogical_views.lesson_feedbacks, name='pedagogical_lesson_feedbacks'),
    path('gestao-pedagogica/feedback-aula/<int:lesson_id>/', pedagogical_views.lesson_feedback_edit, name='pedagogical_lesson_feedback_edit'),
    path('gestao-pedagogica/cursos/', pedagogical_views.courses_list, name='pedagogical_courses'),
    path('gestao-pedagogica/cursos/sincronizar-sponte/', pedagogical_views.courses_sync_sponte, name='pedagogical_courses_sync_sponte'),
    path('gestao-pedagogica/cursos/novo/', pedagogical_views.course_create, name='pedagogical_course_create'),
    path('gestao-pedagogica/cursos/<int:course_id>/editar/', pedagogical_views.course_edit, name='pedagogical_course_edit'),
    path('gestao-pedagogica/cursos/<int:course_id>/alternar-status/', pedagogical_views.course_toggle, name='pedagogical_course_toggle'),
    path('gestao-pedagogica/salas/', pedagogical_views.rooms_list, name='pedagogical_rooms'),
    path('gestao-pedagogica/salas/novo/', pedagogical_views.room_create, name='pedagogical_room_create'),
    path('gestao-pedagogica/salas/<int:room_id>/editar/', pedagogical_views.room_edit, name='pedagogical_room_edit'),
    path('gestao-pedagogica/salas/<int:room_id>/alternar-status/', pedagogical_views.room_toggle, name='pedagogical_room_toggle'),
    path('gestao-pedagogica/horarios/', pedagogical_views.time_slots_list, name='pedagogical_time_slots'),
    path('gestao-pedagogica/horarios/novo/', pedagogical_views.time_slot_create, name='pedagogical_time_slot_create'),
    path('gestao-pedagogica/horarios/<int:slot_id>/editar/', pedagogical_views.time_slot_edit, name='pedagogical_time_slot_edit'),
    path('gestao-pedagogica/horarios/<int:slot_id>/alternar-status/', pedagogical_views.time_slot_toggle, name='pedagogical_time_slot_toggle'),
    path('gestao-pedagogica/feriados-recessos/', pedagogical_views.holidays_list, name='pedagogical_holidays'),
    path('gestao-pedagogica/feriados-recessos/novo/', pedagogical_views.holiday_create, name='pedagogical_holiday_create'),
    path('gestao-pedagogica/feriados-recessos/<int:holiday_id>/editar/', pedagogical_views.holiday_edit, name='pedagogical_holiday_edit'),
    path('gestao-pedagogica/feriados-recessos/<int:holiday_id>/alternar-status/', pedagogical_views.holiday_toggle, name='pedagogical_holiday_toggle'),
    path('gestao-pedagogica/alunos/', pedagogical_views.students_list, name='pedagogical_students'),
    path('gestao-pedagogica/alunos/importar-sponte/', pedagogical_views.students_import_sponte, name='pedagogical_students_import_sponte'),
    path('gestao-pedagogica/alunos/novo/', pedagogical_views.student_create, name='pedagogical_student_create'),
    path('gestao-pedagogica/alunos/<int:student_id>/editar/', pedagogical_views.student_edit, name='pedagogical_student_edit'),
    path('gestao-pedagogica/alunos/<int:student_id>/alternar-status/', pedagogical_views.student_toggle, name='pedagogical_student_toggle'),
    path('tipos-usuario/', user_views.positions_list, name='positions_list'),
    path('tipos-usuario/novo/', user_views.position_create, name='position_create'),
    path('tipos-usuario/<int:position_id>/editar/', user_views.position_edit, name='position_edit'),
    path('usuarios/', user_views.users_list, name='employees_list'),
    path('usuarios/novo/', user_views.user_create, name='employee_create'),
    path('usuarios/<int:user_id>/editar/', user_views.user_edit, name='employee_edit'),
    path('usuarios/<int:user_id>/senha/', user_views.user_reset_password, name='employee_reset_password'),
    path('senha/alterar/', RequiredPasswordChangeView.as_view(), name='password_change'),
    path('senha/alterada/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
]
