# Generated by Django 5.2.1 on 2026-05-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_merge_userprofile_password_and_nominal_registration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checklistoccurrence',
            new_name='checklists__date_400874_idx',
            old_name='checklists_c_date_3e8c3d_idx',
        ),
        migrations.RenameIndex(
            model_name='checklistoccurrence',
            new_name='checklists__positio_e8cc18_idx',
            old_name='checklists_c_positio_6e83fe_idx',
        ),
        migrations.AlterField(
            model_name='checklistoccurrence',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/%Y/%m/', verbose_name='Arquivo de evidência legado'),
        ),
    ]
