# Generated by Django 5.2.1 on 2026-05-31 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_rename_checklists_c_date_3e8c3d_idx_checklists__date_400874_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('VACATION', 'Férias'), ('JUSTIFIED', 'Ausência justificada')], max_length=20, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(verbose_name='Fim')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_absences', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='checklists.userprofile')),
            ],
            options={
                'verbose_name': 'Ausência de colaborador',
                'verbose_name_plural': 'Ausências de colaboradores',
                'ordering': ['-start_date', 'profile__display_name'],
                'indexes': [models.Index(fields=['start_date', 'end_date', 'active'], name='checklists__start_d_4a968e_idx'), models.Index(fields=['profile', 'start_date', 'end_date'], name='checklists__profile_4456b7_idx')],
            },
        ),
    ]
