# Generated by Django 5.2.1 on 2026-05-31 17:12

import django.db.models.deletion
from django.db import migrations, models


def fill_existing_metric_metadata(apps, schema_editor):
    MetricType = apps.get_model('checklists', 'MetricType')
    for metric in MetricType.objects.select_related('position').iterator():
        area = 'Geral'
        if metric.position_id and metric.position:
            area = metric.position.name[:70]
        metric.area = area
        metric.frequency = 'MONTHLY'
        metric.save(update_fields=['area', 'frequency'])


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_rename_status_event_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrictype',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metric_types', to='checklists.tasktemplate'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='area',
            field=models.CharField(default='Operacional', max_length=70, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Diário'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('ANNUAL', 'Anual')], default='MONTHLY', max_length=20, verbose_name='Frequência'),
        ),
        migrations.RunPython(fill_existing_metric_metadata, migrations.RunPython.noop),
    ]
