# Generated by Django 5.2.1 on 2026-05-31 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0011_metrictype_area_frequency_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('CREATE', 'Adicionar atividade'), ('DEACTIVATE', 'Desativar atividade')], max_length=20, verbose_name='Tipo de solicitação')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=20, verbose_name='Status')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('expected_result', models.CharField(blank=True, max_length=300, verbose_name='Resultado esperado')),
                ('frequency', models.CharField(choices=[('DAILY', 'Diária'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('ANNUAL', 'Anual'), ('BIWEEKLY', 'Quinzenal'), ('CONDITIONAL', 'Condicional')], default='DAILY', max_length=20, verbose_name='Recorrência')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')], default=0, verbose_name='Dia da semana')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Fim')),
                ('requires_evidence', models.BooleanField(default=True, verbose_name='Exige evidência')),
                ('evidence_required', models.CharField(blank=True, max_length=300, verbose_name='Evidência exigida')),
                ('proof_location', models.CharField(blank=True, max_length=300, verbose_name='Onde comprovar')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('justification', models.CharField(blank=True, max_length=500, verbose_name='Justificativa')),
                ('review_note', models.CharField(blank=True, max_length=500, verbose_name='Observação da revisão')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('created_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creation_suggestions', to='checklists.tasktemplate', verbose_name='Atividade criada')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_suggestions', to='checklists.position')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_suggestions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activity_suggestions', to=settings.AUTH_USER_MODEL)),
                ('target_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivation_suggestions', to='checklists.tasktemplate', verbose_name='Atividade indicada para inativação')),
            ],
            options={
                'verbose_name': 'Sugestão de atividade',
                'verbose_name_plural': 'Sugestões de atividades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'request_type'], name='checklists__status_177868_idx'), models.Index(fields=['position', 'status'], name='checklists__positio_49cb53_idx'), models.Index(fields=['created_at'], name='checklists__created_9998e5_idx')],
            },
        ),
    ]
