# Generated by Django 5.2.1 on 2026-05-31 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0012_activity_suggestions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='new_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='Valores novos'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_label',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nome/descrição do item'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='previous_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='Valores anteriores'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='checklists__created_57fa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['object_type', 'action'], name='checklists__object__8b2e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['actor', 'created_at'], name='checklists__actor_i_b39b1f_idx'),
        ),
    ]
