# Generated by Django 5.2.1 on 2026-05-31 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0013_expand_activity_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_provider', models.CharField(choices=[('NONE', 'Somente backup local'), ('GOOGLE_DRIVE', 'Google Drive'), ('ONEDRIVE', 'OneDrive')], default='NONE', max_length=20, verbose_name='Destino em nuvem')),
                ('remote_path', models.CharField(blank=True, help_text='Exemplo: gdrive:MyRobotBackups/checklist ou onedrive:MyRobotBackups/checklist.', max_length=255, verbose_name='Caminho remoto rclone')),
                ('retention_days', models.PositiveIntegerField(default=30, verbose_name='Retencao local em dias')),
                ('active', models.BooleanField(default=False, verbose_name='Enviar backup para nuvem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracao de backup',
                'verbose_name_plural': 'Configuracoes de backup',
            },
        ),
    ]
