# Generated by Django 5.2.1 on 2026-05-31 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0014_backupconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfiguration',
            name='backup_time',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Horario diario do backup'),
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='last_scheduled_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo backup agendado'),
        ),
    ]
