# Generated by Django 5.2.1 on 2026-06-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0021_commercial_follow_up_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialopportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação da oportunidade'),
        ),
    ]
