# Generated by Django 5.2.1 on 2026-06-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0025_pedagogical_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialopportunity',
            name='interest_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_opportunities', to='checklists.course', verbose_name='Interesse em curso'),
        ),
        migrations.AddField(
            model_name='commercialopportunity',
            name='interest_type',
            field=models.CharField(blank=True, choices=[('partnership', 'Parceria'), ('product', 'Produto'), ('event', 'Evento'), ('other', 'Outros')], max_length=30, verbose_name='Tipo de interesse'),
        ),
        migrations.AddField(
            model_name='commercialopportunity',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
