# Generated by Django 5.2.1 on 2026-06-29 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0026_commercialopportunity_interest_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='external_id',
            field=models.CharField(blank=True, max_length=160, verbose_name='ID externo'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='source',
            field=models.CharField(choices=[('local', 'Checklist'), ('sponte', 'Sponte')], default='local', max_length=30, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sincronizada em'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['source', 'external_id'], name='lesson_source_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_lesson_source_external'),
        ),
    ]
