# Generated by Django 5.2.1 on 2026-06-29 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0027_lesson_external_id_lesson_source_lesson_synced_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='commercial_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trial_lessons', to='checklists.commercialopportunity', verbose_name='Oportunidade'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='trial_kind',
            field=models.CharField(blank=True, choices=[('experimental', 'Experimental'), ('play', 'Play')], max_length=20, verbose_name='Tipo de aula experimental ou Play'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('regular', 'Matriculado'), ('trial', 'Experimental ou Play')], default='regular', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['commercial_opportunity', 'date'], name='lesson_opp_date_idx'),
        ),
    ]
