# Generated by Django 5.2.1 on 2026-06-29 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0028_lesson_commercial_opportunity_lesson_trial_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality_score', models.PositiveSmallIntegerField(choices=[(10, 'Sim'), (5, 'Não')], verbose_name='Pontualidade')),
                ('assembly_comment', models.TextField(verbose_name='Montagem')),
                ('assembly_score', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Montagem nota')),
                ('has_programming', models.BooleanField(default=False, verbose_name='A aula teve programação?')),
                ('programming_comment', models.TextField(blank=True, verbose_name='Programação')),
                ('programming_score', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Programação nota')),
                ('participation_comment', models.TextField(verbose_name='Interesse/Participação')),
                ('participation_score', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Interesse/Participação nota')),
                ('behavior_comment', models.TextField(verbose_name='Comportamento')),
                ('behavior_score', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Comportamento nota')),
                ('general_comment', models.TextField(verbose_name='Comentário geral')),
                ('general_score', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Comentário geral nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_feedbacks_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='checklists.lesson', verbose_name='Aula')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_feedbacks_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Feedback de aula',
                'verbose_name_plural': 'Feedbacks de aula',
                'ordering': ['-lesson__date', '-lesson__start_time'],
            },
        ),
    ]
