# Generated by Django 5.2.1 on 2026-06-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0031_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('done', 'Realizada'), ('cancelled', 'Cancelada'), ('absent', 'Falta'), ('rescheduled', 'Reagendada'), ('not_given', 'Não dada')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
    ]
