# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0032_alter_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonfeedback',
            name='module_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Módulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonfeedback',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], default=1, verbose_name='Aula'),
            preserve_default=False,
        ),
    ]
