# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0034_remove_evidence_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='ID externo'),
        ),
        migrations.AddField(
            model_name='course',
            name='source',
            field=models.CharField(choices=[('local', 'Checklist'), ('sponte', 'Sponte')], default='local', max_length=30, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='course',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sincronizado em'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_course_source_external'),
        ),
    ]
