# Generated by Codex on 2026-06-29

from django.db import migrations, models


def normalize_lesson_statuses(apps, schema_editor):
    Lesson = apps.get_model('checklists', 'Lesson')
    Lesson.objects.filter(status='scheduled').update(status='not_given')
    Lesson.objects.filter(status='rescheduled').update(status='cancelled')


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0035_course_source_external_id_synced_at_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_lesson_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(
                choices=[
                    ('done', 'Presença'),
                    ('absent', 'Falta'),
                    ('not_given', 'Não dada'),
                    ('cancelled', 'Cancelada'),
                ],
                default='not_given',
                max_length=20,
                verbose_name='Status',
            ),
        ),
    ]
