# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0036_lesson_sponte_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialopportunity',
            name='automation_key',
            field=models.CharField(blank=True, db_index=True, max_length=160, verbose_name='Chave de automação'),
        ),
        migrations.AddConstraint(
            model_name='commercialopportunity',
            constraint=models.UniqueConstraint(
                condition=models.Q(('automation_key', ''), _negated=True),
                fields=('automation_key',),
                name='unique_commercial_opportunity_automation_key',
            ),
        ),
    ]
