# Generated by Codex on 2026-06-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0038_adjust_timeslot_end_times'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedagogicalReportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='Módulo')),
                ('lesson_number', models.PositiveSmallIntegerField(choices=[(1, '1'), (15, '15')], verbose_name='Aula')),
                ('due_date', models.DateField(verbose_name='Prazo')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedagogical_reports_completed', to=settings.AUTH_USER_MODEL, verbose_name='Concluído por')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedagogical_report_tasks', to='checklists.course', verbose_name='Curso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedagogical_reports_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pedagogical_report_task', to='checklists.lessonfeedback', verbose_name='Feedback de referência')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedagogical_report_tasks', to='checklists.pedagogicalstudent', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Relatório pedagógico',
                'verbose_name_plural': 'Relatórios pedagógicos',
                'ordering': ['completed', 'due_date', 'student__name', 'module_number', 'lesson_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='pedagogicalreporttask',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'module_number', 'lesson_number'), name='unique_pedagogical_report_task_per_student_course_step'),
        ),
    ]
