# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0039_pedagogicalreporttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedagogicalreporttask',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(choices=[(8, '8'), (15, '15')], verbose_name='Aula'),
        ),
    ]
