# Generated by Django 5.2.1 on 2026-07-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0046_spontesyncjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrictype',
            name='attention_points',
            field=models.TextField(blank=True, verbose_name='Pontos de atenção'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='data_source',
            field=models.CharField(blank=True, max_length=180, verbose_name='Fonte de dados'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='deliverables',
            field=models.TextField(blank=True, verbose_name='Entregáveis'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Definição'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='formula',
            field=models.TextField(blank=True, verbose_name='Fórmula de cálculo'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='grafana_dashboard_uid',
            field=models.CharField(blank=True, max_length=120, verbose_name='UID do dashboard Grafana'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='grafana_last_error',
            field=models.TextField(blank=True, verbose_name='Último erro Grafana'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='grafana_last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização Grafana'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='grafana_panel_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do painel Grafana'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='grafana_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('SYNCED', 'Sincronizado'), ('FAILED', 'Falhou'), ('DISABLED', 'Desativado')], default='PENDING', max_length=20, verbose_name='Status da sincronização Grafana'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='target_direction',
            field=models.CharField(choices=[('AT_LEAST', 'Maior ou igual'), ('AT_MOST', 'Menor ou igual'), ('RANGE', 'Faixa'), ('INCREASE', 'Aumento'), ('EXACT', 'Valor exato')], default='AT_LEAST', max_length=20, verbose_name='Direção da meta'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='target_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Meta máxima'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='target_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Meta mínima'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='target_text',
            field=models.CharField(blank=True, max_length=180, verbose_name='Meta/alvo textual'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='visualization_type',
            field=models.CharField(choices=[('AUTO', 'Automático'), ('TIMESERIES', 'Série temporal'), ('GAUGE', 'Medidor'), ('STAT', 'Número destaque'), ('BAR', 'Barras'), ('TABLE', 'Tabela')], default='AUTO', max_length=20, verbose_name='Visualização Grafana'),
        ),
    ]
