# Generated by Django 5.2.1 on 2026-07-02 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0047_metrictype_attention_points_metrictype_data_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255, verbose_name='Arquivo de origem')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Início do período')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Fim do período')),
                ('total_responses', models.PositiveIntegerField(default=0, verbose_name='Respostas válidas')),
                ('promoters', models.PositiveIntegerField(default=0, verbose_name='Promotores')),
                ('passives', models.PositiveIntegerField(default=0, verbose_name='Neutros/passivos')),
                ('detractors', models.PositiveIntegerField(default=0, verbose_name='Detratores')),
                ('promoter_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='% de promotores')),
                ('nps_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='NPS')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('metric_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nps_imports', to='checklists.metricrecord')),
            ],
            options={
                'verbose_name': 'Importação NPS',
                'verbose_name_plural': 'Importações NPS',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='NPSResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=80, verbose_name='ID externo')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início da resposta')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão da resposta')),
                ('student_name', models.CharField(blank=True, max_length=180, verbose_name='Aluno')),
                ('responsible_name', models.CharField(blank=True, max_length=180, verbose_name='Responsável')),
                ('original_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota original')),
                ('score_0_10', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota normalizada 0-10')),
                ('category', models.CharField(choices=[('PROMOTER', 'Promotor'), ('PASSIVE', 'Neutro/passivo'), ('DETRACTOR', 'Detrator')], max_length=20, verbose_name='Categoria')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Linha original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.npsimport')),
            ],
            options={
                'verbose_name': 'Resposta NPS',
                'verbose_name_plural': 'Respostas NPS',
                'ordering': ['-completed_at', 'student_name'],
            },
        ),
    ]
